# Generated by Django 5.1.1 on 2024-10-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='job_experience',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='job_title',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
